### ISSUE TITLE
expand WordPress CMS search strings 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1033]
Ideas: 

- look for /wp-content/ in the source code 
- look for /wp-json/ in the headers (do you need specific ones to look at?)
- sitemap ends in /wp-sitemap.xml

**Comment by akuny** [comment]
I added the first two items in the list to the current scan, but the third one is a little tricky since the CMS scan currently just handles an HTTPResponse object that is passed to it by the main scan routine. It would require some rework to update that scan to also check for the existence of a `/wp-sitemap.xml` path.

**Comment by gbinal** [comment]
sure!  thanks!

**Comment by gbinal** [comment]
Actually, going to keep this open for a moment while checking to see how many this has changed.

**Comment by gbinal** [comment]
Was 1,078/29,645.  Now 1,298/28,883.
