### ISSUE TITLE
index oddity

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1059]
`telework.gov` appears twice in the [index](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list.csv).

It's small but worth figuring out why it's happening.

**Comment by akuny** [comment]
This duplicate entry has been removed. The reason it appeared twice was because it is included in this file, which is incorporated into the dataset after deduplication: https://github.com/GSA/federal-website-index/blob/main/criteria/ignore-except.csv.

I updated the builder script to run a final deduplication on the list before saving it to CSV.

**Comment by gbinal** [comment]
Great work.  Thanks!
