### ISSUE TITLE
tidy up (delete) bielen cloud.gov space

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1093]

**Comment by luke-at-flexion** [comment]
Still working on this, but running into some issues.

1. We cannot delete the `bielen` space because it contains an S3 bucket that is not empty.
2. CloudFoundry _requires_ buckets to be manually cleared before they can be deleted; see: https://github.com/cloud-gov/s3-broker/issues/8

But, we're looking for a workaround.

**Comment by luke-at-flexion** [comment]
We found a way around it. We created temporary AWS credentials for the bucket, used those to remove all objects from the bucket, and then we were able to delete the `bielen` space.

All done :)

**Comment by gbinal** [comment]
Great, thanks!
