### ISSUE TITLE
Review and possibly act on cloud.gov email from 9-5

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1143]
re: "Action required: Pending database engine version retirement and upgrades"

**Comment by luke-at-flexion** [comment]
We're going to lean toward having Cloud.gov do the upgrade for us, and I will respond to the email to notify them of that.

However, before I do, I am going to investigate to make sure we can restore the data (or otherwise repopulate it) before doing the upgrade.

One snag with more modern versions of Postgres is that SSL connections to Postgres servers is now mandatory, by default, so complications may arise that will prevent our app from connecting to the upgraded instance. I am going to investigate this, as well, and we may end up running two Postgres instances for a short time, if zero-down-time is a priority.

**Comment by gbinal** [comment]
great work!

**Comment by luke-at-flexion** [comment]
*Cleanup Tasks:*
- Rename new Postgres instance
- Decommission original Postgres instance
- Update applications to remove the binding to the old instance
- Update code to ensure the proper database is being connected to after everything is cleaned up
