### ISSUE TITLE
review updated log4j instructions

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#124]
(details in slack)

**Comment by wesley-dean-gsa** [comment]
I used [ack](https://beyondgrep.com/) to scan the [site-scanning-engine repo](https://github.com/GSA/site-scanning-engine) for "log4" (which would match "Log4j") and it came back with no matches.

Also, I see that [dependabot](https://github.com/apps/dependabot) is configured so that any dependencies on older, affected libraries would be caught.  The list of open PRs does not include any Log4j dependency bumps.

Therefore, I'm fairly confident that the Log4j vulnerability will not affect our code directly.  It could, however, affect the underlying platform (e.g,. AWS); however, mitigation of those issues would take place outside of our code and it's dependencies.
