### ISSUE TITLE
ensure column order again

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#195]
The order of the columns after the new work (as seen in the [3-1 export](https://docs.google.com/spreadsheets/d/12h_T7QW-3LqP0uFvbldZZRYR7kP6Y3LkICcp7PJxtfA/edit#gid=1626450569) is right), but has since gotten out of whack (see [3-9 export](https://docs.google.com/spreadsheets/d/1sAR6gEeYoQfDgg0pErPxgp3gqbL3a9_x3tQxCdEa_AQ/edit#gid=965773615)).  

We should investigate why this happened, undo whatever caused it, and figure out how to ensure it doesn't happen again.

**Comment by danielnaab** [comment]
Hi @gbinal this is because the CSV branch hasn't been merged yet. @wesley-dean-gsa if you get a chance, could you review and deploy? https://github.com/GSA/site-scanning-engine/pull/162 Thanks!

BTW, I just turned on the "update branch" merge button setting for PRs, to merge the target into the source branch via the UI.

**Comment by gbinal** [comment]
Ah!  Fair enough.  Thanks!

**Comment by gbinal** [comment]
this should be done now!

**Comment by gbinal** [comment]
done!
