### ISSUE TITLE
Add new calculation/analysis endpoints to the API

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#261]
- [Brainstorming this here](https://github.com/GSA/site-scanning/issues/256)  
- [medium priority (1), needs to be fleshed out more]
- QC and analysis 
- E.g. Sheet [1](https://docs.google.com/spreadsheets/u/1/d/1Pm0mUz7BXCPv5mLqkU4FNuAA2buhfdNV5cOl4IqWtew/edit?usp=drive_web&ouid=106023986186241566265), 
- Question - what if this was separate from the API and powered by GitHub Actions

**Comment by gbinal** [comment]
For a first pass at this, here's what we envision: 
* Adding two fields (possibly to the META endpoint - see screenshot below)
* # of agencies (target_url_domain_owners) and # of unique domains (final_url_domain) _for the current query_.  
* The idea being that any query parameters that are added could result in updated results for those two entries. 
* These could be added to the endpoint design outside of the meta section if the engineer thought better.  


![Screenshot 2022-08-26 at 14-07-32 https __api gsa gov](https://user-images.githubusercontent.com/633088/186966197-0c3e60b1-d107-4a32-9554-15d9362e0366.png)

**Comment by gbinal** [comment]
@akuny - fyi, this is now updated with - I think - enough detail to work on.  Want to add it to this sprint?

**Comment by akuny** [comment]
After some investigation on my part, it turns out that the `meta` property returned with API calls is something we get out-of-the-box with the framework's [pagination module](https://github.com/nestjsx/nestjs-typeorm-paginate).

There is not a straightforward way to hook into the pagination function this module performs and add new properties to the `meta` object derived from the same database queries that return the `items` property. Theoretically, we could modify the `meta` property after the database queries have run, but that would involve hitting the database a second time (affecting performance) and would convolute the architecture of the API (affecting maintenance). 

To move forward, I recommend that we consider creating a new endpoint (e.g., `/analyze/`) that clients would hit separately to gain information about the results of a given query, such as the total number of agencies (target_url_domain_owners) and the total number of unique domains (final_url_domain).

**Comment by akuny** [comment]
On 9/6/22, we went live with the an `/analysis` endpoint that lets you filter by:
- Number of agencies (target_url_domain_owners)
- Number of unique domains (final_url_domain) for the current query.

<img width="796" alt="unfiltered-analysis-request" src="https://user-images.githubusercontent.com/13356991/188932207-603a4cdb-f3d1-4e32-8745-b0d63f290952.png">
<img width="794" alt="filtered-analysis-request" src="https://user-images.githubusercontent.com/13356991/188932214-31dbc655-969e-4834-9044-bef1ca98a5fa.png">

**Comment by gbinal** [comment]
Great work!!!

Example queries: 
* [/analysis](https://api.gsa.gov/technology/site-scanning/v1/analysis?api_key=DEMO_KEY)
* [/analysis?target_url_domain=gsa.gov](https://api.gsa.gov/technology/site-scanning/v1/analysis?api_key=DEMO_KEY&target_url_domain=gsa.gov)
* [/analysis?final_url_domain=gsa.gov](https://api.gsa.gov/technology/site-scanning/v1/analysis?api_key=DEMO_KEY&final_url_domain=gsa.gov)
* [/analysis?target_url_agency_owner=General%20Services%20Administration](https://api.gsa.gov/technology/site-scanning/v1/analysis?api_key=DEMO_KEY&target_url_agency_owner=General%20Services%20Administration)
