### ISSUE TITLE
update target URL list creation script

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#287]
It looks like Branch, Bureau, and Bureau Code aren't getting applied to any of the entries that aren't in the .gov registry list.

**Comment by akuny** [comment]
I think the issue here is that the [pulse subdomain list](https://raw.githubusercontent.com/GSA/federal-website-index/main/data/snapshots/1-13-22/pulse-subdomains-snapshot-06-08-2020-https.csv) does not have a `bureau` column, so the script that builds the list does not have any value to key off of for the `bureau_code`.

We should break down how these two fields are assigned to the pulse subdomain list when the target URL list is created manually so that we can update the script accordingly.

**Comment by gbinal** [comment]
What we do is isolate the base domain from each website, then refer to the list of .gov domains to see what agencies and bureaus are associated with it.

**Comment by akuny** [comment]
When you have a chance, please take another look at the dataset. I've added logic to populate agency and bureau data derived from the .gov domains as described above.

**Comment by gbinal** [comment]
We're still working on this.

**Comment by gbinal** [comment]
should be good now.  closing.
