### ISSUE TITLE
Address API issue 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#427]

**Comment by akuny** [comment]
On 4/11/23, a user reported that `touchpoints.digital.gov` was not being returned by the site scanning API. Investigation showed that although this URL was present in the DAP datasource used by the federal-website-index [builder script](https://github.com/GSA/federal-website-index), the URL was not in the resulting final list. 

This is because a subset of URLs were erroneously scrubbed of their `base_domain` value during the process of merging the various data sources together. This error has been fixed, the federal-website-index final URL list now includes `touchpoints.digital.gov`, and the snapshots and API both include results for this URL.

**Comment by gbinal** [comment]
great work!
