### ISSUE TITLE
CMS to scan for: Wagtail

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#475]
From emailed feedback:
`I used to work at CFPB a few months ago and I know they use Wagtail CMS, but no CMS is listed for them. Do you have a different list of all CMS’s in use or clarity on why some may be missing? (I know the list on [digital.gov](http://digital.gov/) is outdated.)`

**Comment by akuny** [comment]
We're currently scanning for CMSs by looking for (1) certain HTML snippets that may appear in the response body, and (2) certain headers that may be present in the HTTP response. We currently don't have any data in either of those categories for Wagtail CMS, which is why we're not detecting it at this point.

**Comment by gbinal** [comment]
Closing in favor of #379
