### ISSUE TITLE
complete 2x sets of document requests

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#599]
From Phil (slack) and Jacob (email).

**Comment by laurenancona** [comment]
Document 1 - Slide for JP:
As we work to establish our new division over the next few months, there will be data calls. I prefer to have everyone work through their branch chiefs for these but we have a quick turnaround.

I need to provide a short division overview to TTS leadership the week of the 18th. I've been asked to come with a slide deck containing 1 slide covering each program. Program leads, since you know your programs, I'd like for YOU to provide me with a slide with--
quick program overview (mission, FTE, accomplishments)
a goal for FY24

**Comment by gbinal** [comment]
done!
