### ISSUE TITLE
Possible false negatives for the viewport scan 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#664]
Our results show them as negative but I'm seeing a viewport tag in the source code.  Is it possible that some part of the criteria is too exacting (especially what comes after `content=`).  E.g. both of the below have a space in their content sections... (shrugs)

Here are two examples.  

* web.fnal.gov
* https://dlsr-workshop-2014.aps.anl.gov

**Comment by akuny** [comment]
In the case of web.fnal.gov, I'm not seeing a meta tag for the viewport when poking around the page source in Chrome DevTools.

In the case of https://dlsr-workshop-2014.aps.anl.gov/...

`<meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">`

...does not include the text "width=" in the content attribute's text value, so that's why it's failing to meet the criteria specified in the scan. 

Here is the exact DOM query being used in the scan ([source file here](https://github.com/GSA/site-scanning-engine/blob/27d1309d0cb8627786c8de968a95248e5d94b63d/libs/core-scanner/src/scans/mobile.ts#L20)):

`document.querySelector("head > meta[name='viewport'][content*='width=']");`

And here are the criteria Lighthouse uses ([see here](https://developer.chrome.com/docs/lighthouse/pwa/viewport/)):

> A page fails the audit unless all of these conditions are met:
> - The document's `<head>` contains a `<meta name="viewport">` tag.
> - The viewport meta tag contains a `content` attribute.
> - The `content` attribute's value includes the text `width=`.

**Comment by gbinal** [comment]
ah!  this makes sense.  Thank you!!
