### ISSUE TITLE
investigate false negatives for CMS scans 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#954]
It's very possible that this is just b/c our current library of snippets is incomplete, but in case these are actually the results of bugs or our scans failing, let's investigate that.  

* ssa.gov - they say that they are using Acquia's drupal.

**Comment by akuny** [comment]
Drupal isn't showing up as a CMS for ssa.gov because it does not meet the criteria we're scanning for:

```javascript
  {
    cms: 'Drupal',
    html: '<(?:link|style)[^>]+"/sites/(?:default|all)/(?:themes|modules)/',
    headers: [
      { key: 'X-Drupal-Cache', value: '' },
      { key: 'X-Generator', value: '^Drupal(?:\\s([\\d.]+))?\\;version:\\1' },
    ],
  }
```

However, there is a meta "Generator" element in the response body that explicitly states the site has been built using Drupal:

`<meta name="Generator" content="Drupal 10 (https://www.drupal.org)">`

Testing indicates that adding this regex picks up the fact that Drupal is used for ssa.gov:

`<meta[^>]*name="Generator"[^>]*content="[^"]*drupal[^"]*"[^>]*>`

**Comment by gbinal** [comment]
rock!  please add that one in, too.  

Good man.

**Comment by gbinal** [comment]
great work!  [I see it now](https://api.gsa.gov/technology/site-scanning/v1/websites/ssa.gov?API_KEY=DEMO_KEY).

**Comment by gbinal** [comment]
Closing until others are brought to our attention
